### ISSUE TITLE
Can't find adapter with cec.dll 4.0.0.0

### ISSUE THREAD

**Issue by kanedauy** [Pulse-Eight/cec-dotnet#3]
I have compiled the cec.dll 4.0.0.0, but I cant find the adapter, with the cec.dll 3.0.0.0 no problem.
The proyect libcec no longer generates a LibCecSharp.dll, is there any way to generate an updated version of LibCecSharp.dll that works with cec.dll 4.0.0.0?

**Comment by opdenkamp** [comment]
this has been addressed in 4.0.2 which will be available soon
